name: example-environment
channels:
  - conda-forge
dependencies:
  - numpy
  - psutil
  - toolz
  - matplotlib
  - dill
  - pandas
  - partd
  - bokeh
  - dask
  - openpyxl
  - scipy
  - datetime
  - dateutil
  - statsmodels
  - sklearn
